apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config-user
data:
  application.properties: |
    server.port=9099
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.open-in-view=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.show-details=always
    management.metrics.distribution.slo.http.server.requests=10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
    management.prometheus.metrics.export.enabled=true
    management.endpoints.web.exposure.include=*
    management.health.db.enabled=true
    management.health.db.datasource=${SPRING_DATASOURCE_URL}
    billing.service.url = http://billing-app-service.{{ .Release.Namespace }}.svc.cluster.local
