spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083  #or otus-auth-service.otus.svc.cluster.local
          predicates:
            - Path=/login
#            - Path=/refresh
#          filters:
#            - StripPrefix=1

        - id: user-service-open
          uri: http://localhost:9099 #or otus-user-service.otus.svc.cluster.local
          predicates:
            - Path=/user/register

        - id: user-service-secure
          uri: http://localhost:9099 #or otus-user-service.otus.svc.cluster.local
          predicates:
            - Path=/user/**
          filters:
            - CheckAuthToken  # Удалили RemoveRequestHeader

        - id: billing-service
          uri: http://localhost:8082 #or kubernetes service billing-service.otus.svc.cluster.local
          predicates:
            - Path=/billing/**
          filters:
            - CheckAuthToken

        - id: order-service
          uri: http://localhost:8081 #or kubernetes service order-service.otus.svc.cluster.local
          predicates:
            - Path=/orders/**
          filters:
            - CheckAuthToken
jwt:
  secret: bXktc3RyaW5n


