server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include=*:

billing:
  service:
    url: http://localhost:8082