apiVersion: v2
name: kafka
version: 0.1.0
appVersion: "2.8.0"
description: A Helm chart for Apache Kafka

dependencies:
  - name: kafka
    version: 25.0.0
    repository: "https://charts.bitnami.com/bitnami"