apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  application.yaml: |
    server:
      port: 8082
    spring:
      jpa:
        hibernate:
          ddl-auto: update
