server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: http://localhost:9092

billing:
  service:
    url: http://localhost:8082

delivery:
  service:
    url: http://localhost

inventory:
  service:
    url: http://localhost

payment:
  service:
    url: http://localhost

