server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include=*: